### ISSUE TITLE
iOS compile error

### ISSUE THREAD

**Issue by bagelcafe** [smartscenes/multiscan#5]
Hi, thank you for your work to share the codes in this project.

I downloaded your project code and compiled iOS app on Mac OS 10.15 with xcode 12.5.
I met the following error in CameraViewControllor.swift.

case .arCamera:
            
            if #available(iOS 14.0, *) {
                
                recordingManager = ARCameraRecordingManager()
                let session = recordingManager.getSession() as! ARSession
                let arView = ARView()
                
                arView.session = session
                → (error) Value of type 'ARView' has no member 'session'
                
                arView.renderOptions = [.disablePersonOcclusion, .disableDepthOfField, .disableMotionBlur]
                 → (error) Reference to member 'disableDepthOfField' , cannot be resolved without a contextual type

                arView.automaticallyConfigureSession = false
                → (error) Value of type 'ARView' has no member 'automaticallyConfigureSession'

                 arView.debugOptions.insert(.showSceneUnderstanding)
                 → (error) Type 'ARView.DebugOptions.Element' (aka 'ARView.DebugOptions') has no member 'showSceneUnderstanding'

Technically, ARView can read Scene class property, but my xcode generated compile error in this case.
Can you help me avoiding these compile error in this file?
In advance, thank you for your supporting.

Regards,

**Comment by SamMaoYS** [comment]
Hi @bagelcafe, thank you for your interest. 

I tried to compile the ios scanner app on macOS 12.4 with Xcode 13.4.1, with an actual iPhone 12 Pro device (iOS 15) and an iPad Pro (iPadOS 15). I cannot reproduce the error you showed above. 

I found this [stack overflow post: ARKit Plane Detection - Value of type 'ARView' has no member 'session'](https://stackoverflow.com/questions/56973063/arkit-plane-detection-value-of-type-arview-has-no-member-session), it mentions "_You get this error if your build destination is set to a Simulator. You need to select either an Actual Device or Generic iOS Device_."

Then I also tried to compile the ios scanner app on macOS 12.4 with Xcode 13.4.1, with iOS Simulators set as iPhone 12 pro (I also tested with iPhone 12). And I cannot reproduce the error you showed above. I am not sure if this is because I am using the newer version of Xcode, so I don't get the error when building with simulators.

If you can kindly share us with your settings: whether you are building with simulators or an actual device, and which version of the OS, the actual model device, etc. We can better help you find the root cause of the issue. Thank you!

All the best

**Comment by bagelcafe** [comment]
Hi @SamMaoYS ,

Thank you for your comment and I upgrade Mac OS 10.15 to 12.6.2 on notebook. Also, xcode version was upagrded to 14.1 version.
In the end, those compile error with arView were resolved via update the version of Mac OS and Xcode. The app was successfully compiled and installed to iPad pro.

I appreciated your comment and effort with this issue.

Best Regards,
